### ISSUE TITLE
add dtype input fields

### ISSUE THREAD

**Issue by KevinDukelow5** [colpal/dataEng-container-tools#9]
ref: https://github.com/colpal/cp-saa-external-sales/blob/da345221a11d8529f781c61828240771b54aa84f/containers/generic/fill_null_cols/scripts/entrypoint.py#L79

**Comment by alexrsaff** [comment]
ref: https://github.com/colpal/dataEng-container-tools/blob/8e173a6b30c667c75489902e61fd1d90cdd7cc9a/dataEng_container_tools/cla.py#L91-L93
